Facade/DesignPattern.Facade/Models/ErrorViewModel.cs
namespace DesignPattern.Facade.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Facade/DesignPattern.Facade/Controllers/CustomerController.cs
using DesignPattern.Facade.DAL;
using Microsoft.AspNetCore.Mvc;

namespace DesignPattern.Facade.Controllers
{
    public class CustomerController : Controller
    {
        AppDbContext _context = new AppDbContext();

        [HttpGet]
        public IActionResult AddNewCustomer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewCustomer(Customer customer)
        {
            _context.Customers.Add(customer);
            _context.SaveChanges();
            return RedirectToAction("CustomerList");
        }

        public IActionResult CustomerList()
        {
            var values = _context.Customers.ToList();
            return View(values);
        }
    }
}

Facade/DesignPattern.Facade/Controllers/HomeController.cs
using DesignPattern.Facade.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DesignPattern.Facade.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Facade/DesignPattern.Facade/Controllers/OrderController.cs
using DesignPattern.Facade.DAL;
using DesignPattern.Facade.FacadeDesignPattern;
using Microsoft.AspNetCore.Mvc;

namespace DesignPattern.Facade.Controllers
{
    public class OrderController : Controller
    {
        AppDbContext _context = new AppDbContext();
        

        [HttpGet]
        public IActionResult OrderDetailStart()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OrderDetailStart(int customerId, int productId, int orderId, int productCount, decimal productPrice)
        {
            OrderFacede _orderFacede = new OrderFacede();
            _orderFacede.CompleteOrderDetail(customerId, productId, orderId, productCount, productPrice);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult OrderStart()
        {
            return View();
        }

        [HttpPost]
        public IActionResult OrderStart(int customerId)
        {
            OrderFacede _orderFacede = new OrderFacede();
            _orderFacede.CompleteOrder(customerId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Facade/DesignPattern.Facade/Controllers/ProductController.cs
using DesignPattern.Facade.DAL;
using Microsoft.AspNetCore.Mvc;

namespace DesignPattern.Facade.Controllers
{
    public class ProductController : Controller
    {
        AppDbContext _context = new AppDbContext();

        [HttpGet]
        public IActionResult AddNewProduct()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewProduct(Product product)
        {
            _context.Products.Add(product);
            _context.SaveChanges();
            return RedirectToAction("ProductList");
        }

        public IActionResult ProductList()
        {
            var values = _context.Products.ToList();
            return View(values);
        }
    }
}

Facade/DesignPattern.Facade/Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_FacadeLayout.cshtml";
}

<h1>Index</h1>

Facade/DesignPattern.Facade/Views/Order/OrderDetailStart.cshtml
@model DesignPattern.Facade.DAL.OrderDetail
@{
    ViewData["Title"] = "OrderStart";
    Layout = "~/Views/Shared/_FacadeLayout.cshtml";
}

<h1>Sipariş Detay Sayfası</h1>

<div class="container">
    <form method="post">
        <label>Müşteri Id</label>
        <input type="text" asp-for="CustomerId" class="form-control" />
        <br />
        <label>Ürün Id</label>
        <input type="text" asp-for="ProductId" class="form-control" />
        <br />
        <label>Sipariş Id</label>
        <input type="text" asp-for="OrderId" class="form-control" />
        <br />
        <label>Ürün Fiyatı</label>
        <input type="text" asp-for="ProductPrice" class="form-control" />
        <br />
        <label>Ürün Adedi</label>
        <input type="text" asp-for="ProductCount" class="form-control" />
        <br />
        <button class="btn btn-primary">Sipariş Ver</button>
    </form>
</div>

Facade/DesignPattern.Facade/Views/Order/OrderStart.cshtml
@model DesignPattern.Facade.DAL.Order
@{
    ViewData["Title"] = "OrderStart";
    Layout = "~/Views/Shared/_FacadeLayout.cshtml";
}

<h1>Sipariş Detay Sayfası</h1>

<div class="container">
    <form method="post">
        <label>Müşteri Id</label>
        <input type="text" asp-for="CustomerId" class="form-control" />
        <br />
        <button class="btn btn-primary">Sipariş Oluştur</button>
    </form>
</div>

Facade/DesignPattern.Facade/Views/Product/AddNewProduct.cshtml
@model DesignPattern.Facade.DAL.Product
@{
    ViewData["Title"] = "AddNewCustomer";
    Layout = "~/Views/Shared/_FacadeLayout.cshtml";
}

<h1>Yeni Müşteri Girişi</h1>

<div>
    <form method="post">
        <br />
        <label>Ürün Adı</label>
        <input type="text" asp-for="ProductName" class="form-control" />
        <br />
        <label>Stok</label>
        <input type="text" asp-for="ProductStock" class="form-control" />
        <br />
        <label>Fiyatı</label>
        <input type="text" asp-for="ProductPrice" class="form-control" />
        <br />
        <label>Ürün Kategorisi</label>
        <input type="text" asp-for="ProductCategory" class="form-control" />
        <br />
        <button class="btn btn-primary">Ürünü Kaydet</button>
    </form>
</div>

Facade/DesignPattern.Facade/Views/Product/ProductList.cshtml
@model List<DesignPattern.Facade.DAL.Product>
@{
    Layout = "~/Views/Shared/_FacadeLayout.cshtml";
}

<h1>Müşteri Listesi</h1>
<div class="container">
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Ürün Adı</th>
            <th>Stok</th>
            <th>Fiyat</th>
            <th>Kategori</th>
        </tr>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.ProductId</td>
                <td>@customer.ProductName</td>
                <td>@customer.ProductStock</td>
                <td>@customer.ProductPrice</td>
                <td>@customer.ProductCategory</td>
            </tr>
        }
    </table>
    <a asp-controller="Product" asp-action="AddNewProduct" class="btn btn-primary">Yeni Ürün Ekle</a>
</div>

Facade/DesignPattern.Facade/Views/Shared/_FacadeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">FacadeDesign Pattern</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a asp-controller="Customer" asp-action="CustomerList">Müşteriler</a></li>
                <li><a asp-controller="Product" asp-action="ProductList">Ürünler</a></li>
                <li><a href="#">Siparişler</a></li>
                <li><a href="#">Sipariş Detayları</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>

Facade/DesignPattern.Facade/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignPattern.Facade</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesignPattern.Facade.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignPattern.Facade</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DesignPattern.Facade - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>